# Generated by Django 6.0.4 on 2026-04-11 12:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_arabic', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('seats_available', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(default='Egyptian Parliamentary Elections 2024', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Election Configuration',
                'verbose_name_plural': 'Election Configurations',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('party', models.CharField(choices=[('ndp', 'National Democratic Party'), ('wafd', 'Al-Wafd Party'), ('tagammu', 'National Progressive Unionist Party'), ('independent', 'Independent'), ('free_egyptians', 'Free Egyptians Party'), ('future', "Nation's Future Party"), ('republican_peoples', "Republican People's Party")], default='independent', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.district')),
            ],
            options={
                'ordering': ['district', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(db_index=True, help_text='Egyptian National ID - 14 digits', max_length=14, unique=True)),
                ('voiceprint', models.TextField(blank=True, help_text='JSON-encoded MFCC feature vector from Librosa', null=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_auth_timestamp', models.FloatField(blank=True, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='voting.district')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.candidate')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.district')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vote_cast', to='voting.voter')),
            ],
            options={
                'ordering': ['-cast_at'],
            },
        ),
    ]
