# Generated by Django 5.2.13 on 2026-04-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='last_auth_timestamp',
        ),
    ]
