# Generated by Django 6.0.3 on 2026-04-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_squash_ensure_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionconfig',
            options={'verbose_name': 'Election Configuration'},
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voiceprint',
        ),
        migrations.AlterField(
            model_name='voter',
            name='face_descriptor',
            field=models.TextField(blank=True, help_text='128-float face-api.js descriptor as JSON array — no raw images stored', null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='national_id',
            field=models.CharField(db_index=True, help_text='Egyptian National ID — 14 digits', max_length=14, unique=True),
        ),
    ]
